services:
  teste-tecnico-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "teste-tecnico"
      POSTGRES_PASSWORD: "123mudar"
      POSTGRES_DB: "teste-tecnico-db"
    ports:
      - "5432:5432"
    volumes:
      - /teste-tecnico-db-data:/var/lib/postgresql/data
  teste-tecnico-activemq-artemis:
    image: apache/activemq-artemis:2.37.0
    ports:
      - "61616:61616"
      - "8161:8161"